spring:
  application:
    name: dianping

  elasticsearch:
    rest:
      uris: elasticsearch:9200


  datasource:
    url: jdbc:mysql://192.168.99.100:3306/dianping?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true
    username: root #数据库用户名
    password: 123456 #数据库密码
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #Druid连接池
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  #静态资源页面
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
mybatis:
  mapper-locations: '*/**/*Mapper.xml'


canal:
  hostname: 192.168.99.100
  port: 11111
  destination: example
  username: canal
  password: canal

admin:
  email: admin@qq.com
  #123
  encryptPassword: ICy5YqxZB1uWSwcVLSNLcA==
logging:
  level:
    com.dianping: DEBUG
